### ISSUE TITLE
Some GCP options?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [RMHogervorst/scheduling_r_scripts#1]
Thanks for the link to googleCloudRunner, I have been following the other options you've been tweeting as well.

I have had scheduling R scripts as a use case for many years and how I do it has evolved over time, all on GCP that I get quite a few hits to this blog post about https://code.markedmondson.me/4-ways-schedule-r-scripts-on-google-cloud-platform/

Its also one of the use cases on googleCloudRunner https://code.markedmondson.me/googleCloudRunner/articles/usecases.html#run-r-code-on-a-schedule-1 that I use so often I made an RStudio gadget to deploy.  

These days I either use the gadget above or setup a github hook that pushes to Cloud Build, that runs the script in a docker container.  I think the syntax is simple and its very powerful combo.  The setup for GCP is the most difficult part sorting out auth keys etc. but hopefully once thats done the code below is all you need:

https://code.markedmondson.me/googleCloudRunner/reference/cr_deploy_r.html

```r
r_lines <- c("list.files()",
             "library(dplyr)",
             "mtcars %>% select(mpg)",
             "sessionInfo()")

# schedule the script
cr_deploy_r(r_lines, schedule = "15 21 * * *")
```

Or point at an rscript in the git repo, or a local script file, or a Cloud Storage gs:// URL

Anyhow thought you would be interested if you hadn't come across it before, I could submit a pull request perhaps with some examples if you think its appropriate - I'll also be very interested in feedback on how it compares to the other methods you are documenting from a usability perspective.

**Comment by RMHogervorst** [comment]
Yes this is exactly what I was looking for! Yes a pr would be very cool. I really enjoy your posts and packages!

**Comment by RMHogervorst** [comment]
What I'd really like is if we could build a container once, push it to container repositories and schedule those.

**Comment by MarkEdmondson1234** [comment]
That's a pattern I do a lot, have a container that build upon git commit when your code changes, but the schedule itself runs the container in a scheduled cloud build.
